version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "9000:9000"
    container_name: gateway-app

  crawlerservice:
    build: ./services/crawlerservice
    ports:
      - "9002:9002"
    container_name: crawlerservice-app
